version: '3.3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: quanna@251
      MYSQL_DATABASE: eng-examination
      MYSQL_USER: quanna
      MYSQL_PASSWORD: quanna@251
    ports:
      - '3006:3306'